### ISSUE TITLE
language code and local code

### ISSUE THREAD

**Issue by albertp007** [PragmaticMates/django-flatpages-i18n#1]
Hello, would like to let you know that I have encountered a problem with views.flatpage.  Some language codes has a hyphen in it, for which, the corresponding local codes use an underscore instead.  e.g. for traditional chinese, language code sent by the browser in the request object is "zh-tw".  The column that has been created in the flatpage_i18n table is "zh_tw".  Calling the flatpage view after setting the language to zh-tw will result in the following error

```
FieldError at /about/
Cannot resolve keyword 'url_zh-tw' into field. Choices are: content, content_en, content_fr, content_zh_tw, enable_comments, id, registration_required, sites, template_name, title, title_en, title_fr, title_zh_tw, url, url_en, url_fr, url_zh_tw, weight
Request Method: GET
Request URL:    http://127.0.0.1:8000/about/
Django Version: 1.5.1
...
```

For now, to work around it, I added the last line below to blindly replace any '-' with '_', assuming we can't have a hyphen in column names in databases, this works for my project for now.

```
language = request.LANGUAGE_CODE
language_prefix = '/%s' % language
language = language.replace('-', '_')
```

Going by the same logic, I suppose the same problem could potentially happen to the spanish and portuguese folks. (e.g. pt-BR for brazilian portuguese)

If you have other solutions, please kindly let me know!

Lastly, thanks for this wonderful package.  It's exactly what I have been looking for and provides a simple-to-set-up solution for multilingual flatpages.

Regards,

Albert

**Comment by eriktelepovsky** [comment]
Checkout commit 5e6f50d please. It should be supported now.
