### ISSUE TITLE
Does not work with Django 1.10.6

### ISSUE THREAD

**Issue by athom09** [PragmaticMates/django-flatpages-i18n#15]
After following the install instructions I get the the following error when trying to migrate or run any manage.py command:

`File "/Users/athom09/Projects/voyages/voyagesEnv/lib/python2.7/site-packages/flatpages_i18n/models.py", line 1, in <module>
    from builtins import str as text
ImportError: No module named builtins`

**Comment by eriktelepovsky** [comment]
Hi. Does it work for you when you replace 1st line:

``from builtins import str as text``

with this snippet?

```
try:
    from builtins import str as text
except:
    text = unicode
```

**Comment by athom09** [comment]
I replaced the import with the snippet above in the models.py and admin.py.

Now I'm getting:

```
  File "/Users/athom09/Projects/voyages/voyagesEnv/lib/python2.7/site-packages/modeltranslation/translator.py", line 621, in get_options_for_model
    'translation' % model.__name__)
modeltranslation.translator.NotRegistered: The model "FlatPage_i18n" is not registered for translation
```

**Comment by eriktelepovsky** [comment]
Did you put "modeltranslation" in your settings before "django.contrib.admin" ?

http://django-modeltranslation.readthedocs.io/en/latest/installation.html?highlight=django.contrib.admin#installed-apps

**Comment by athom09** [comment]
NOTE: if I ```pip install future```  that gets me past the builtins import error.
Moving ```modeltransitions``` above  contrib.amin in the INSTALLED_APPLICATIONS allowed the migrations to run.

Now I am getting 

```
Invalid template library specified. ImportError raised when trying to load 'flatpages_i18n.templatetags.flatpages_i18n': No module named models
```
when I start the runserver and try to go to the Admin.

**Comment by eriktelepovsky** [comment]
Try to replace line 9 in file templatetags/flatpages_i18n.py:

``from flatpages_i18n.models import FlatPage_i18n, MenuItem``

to 

``from ..models import FlatPage_i18n, MenuItem``

**Comment by athom09** [comment]
think that worked.

Am I correct that the each language has to have it's own url e.g.

```/about/en```   ```/about/fr```

**Comment by eriktelepovsky** [comment]
/en/about/, /fr/sur/ actually
