### ISSUE TITLE
Context processors are not used when rendering flatpage template

### ISSUE THREAD

**Issue by michalochman** [PragmaticMates/django-flatpages-i18n#19]
Looks like the context processors defined in the `TEMPLATE` options of django settings are not loaded and used when rendering flat pages. 

Seems like e53d7a7 fixed it though. Would you be able to release a new version? The latest one is `0.7.0` and it does not include this fix.

**Comment by eriktelepovsky** [comment]
Hi. I've just released version 0.7.1. Check it out ;)

**Comment by michalochman** [comment]
@eriktelepovsky works as intended, thanks!
