### ISSUE TITLE
Django 1.7 compatibility

### ISSUE THREAD

**Issue by luisgruposaii** [PragmaticMates/django-flatpages-i18n#8]
The current "django-flatpages-i18n" doesn't work with the latest Django version (1.7), probably because of its dependence on "South". Have you planned adding compatibility with the latest version of Django?

Regards,
Luis

**Comment by merwok** [comment]
I thinks this was fixed in #9, which is merged but not released yet.

**Comment by eriktelepovsky** [comment]
Thanks. I've just released new version.
